"""ClinicalShield Module 3 — semantic intent verification.

Flags a retrieved document when it diverges from the clinical query in meaning,
or when it carries a known instruction-override marker. Generated by
notebooks/06_module3_intent.ipynb.
"""

import torch
import torch.nn.functional as F

OVERRIDE_MARKERS = ['ignore previous', 'ignore all previous', 'ignore the above', 'disregard the', 'disregard all', 'system override', 'new instruction', 'override:', 'admin:', '[admin]', '[config]', '[system]', 'forget everything', 'forget the', 'prior context is void', 'end of document', 'attention model', 'do not follow', 'your reply must', 'you must instead', 'instead output']

TAU_INTENT = 0.90


def mean_pooled(texts, tokenizer, model, device="cpu", max_len=512, batch=32):
    out = []
    with torch.no_grad():
        for i in range(0, len(texts), batch):
            enc = tokenizer(texts[i:i+batch], truncation=True, padding=True,
                            max_length=max_len, return_tensors="pt").to(device)
            h = model(**enc).last_hidden_state
            m = enc["attention_mask"].unsqueeze(-1).float()
            v = (h * m).sum(1) / m.sum(1).clamp(min=1e-9)
            out.append(F.normalize(v, dim=-1).cpu())
    return torch.cat(out)


def module3(document, query, cosine=None, tau=TAU_INTENT):
    """Returns (flagged, reason). Cosine may be precomputed."""
    if cosine is not None and cosine < tau:
        return True, "similarity"
    low = document.lower()
    for m in OVERRIDE_MARKERS:
        if m in low:
            return True, "marker"
    return False, None
