"""ClinicalShield Module 4 — utility-preserving clinical sanitisation.

Removes adversarial segments while retaining clinical content, scored by the
Clinical Entity Preservation Score. Generated by notebooks/07_module4_ceps.ipynb.

CEPS v2 supersedes v1. v1 measured preservation alone, so a sanitiser that
removed nothing scored 1.0 -- indistinguishable from perfect sanitisation. v2
pairs preservation with adversarial removal and reports their harmonic mean.
"""

import re

CLINICAL_VERBS = ['administer', 'monitor', 'prescribe', 'titrate', 'discontinue', 'adjust', 'reduce', 'increase', 'initiate', 'withhold', 'observe', 'measure', 'assess', 'evaluate', 'consider', 'avoid', 'consult']
ENTITY_CATEGORIES = ['drug_name', 'dosage', 'lab_result', 'vital_sign', 'condition']
GAMMA = 0.95
