"""ClinicalShield Module 1 — encoding-aware ingestion layer.

Detects and decodes Base64, hexadecimal, Unicode escape, URL and Leetspeak
obfuscation before downstream classification. Generated by
notebooks/04_module1_encoding.ipynb.
"""

import re, base64, binascii, urllib.parse, math

B64_RE  = re.compile(r"[A-Za-z0-9+/]{24,}={0,2}")
HEX_RE  = re.compile(r"(?:\\x[0-9a-fA-F]{2}){4,}")
UNI_RE  = re.compile(r"(?:\\u[0-9a-fA-F]{4}){3,}")
URL_RE  = re.compile(r"%[0-9a-fA-F]{2}")
LEET_RE = re.compile(r"\b(?=[a-z]*[0-9])(?=[0-9]*[a-z])[a-z0-9]{4,}\b", re.I)

LEET_MAP = {"4": "a", "3": "e", "1": "i", "0": "o", "5": "s", "7": "t"}


def shannon_entropy(s):
    if not s:
        return 0.0
    counts = {}
    for ch in s:
        counts[ch] = counts.get(ch, 0) + 1
    n = len(s)
    return -sum((c / n) * math.log2(c / n) for c in counts.values())


def looks_like_base64(s):
    """Separate real Base64 from long alphanumeric medical words.

    'oligodeoxynucleotide' matches the Base64 character set but is all one case
    and low entropy. Genuine Base64 mixes case and digits in proportions no
    ordinary medical term does.
    """
    if len(s) < 24:
        return False, 0.0
    has_upper = any(c.isupper() for c in s)
    has_lower = any(c.islower() for c in s)
    has_digit = any(c.isdigit() for c in s)
    ent = shannon_entropy(s)
    score = 0.0
    if has_upper and has_lower:
        score += 0.4
    if has_digit:
        score += 0.2
    if ent > 4.2:
        score += 0.4
    return score >= 0.6, score


def _decodes_to_text(raw):
    """A candidate only counts if it decodes to mostly printable ASCII."""
    try:
        out = raw.decode("utf-8", errors="strict")
    except (UnicodeDecodeError, AttributeError):
        return None
    if not out:
        return None
    printable = sum(1 for c in out if 32 <= ord(c) < 127 or c in "\n\t")
    return out if printable / len(out) > 0.85 else None


def detect_base64(text):
    hits = []
    for m in B64_RE.finditer(text):
        s = m.group()
        ok, conf = looks_like_base64(s)
        if not ok:
            continue
        pad = s + "=" * ((4 - len(s) % 4) % 4)
        try:
            dec = _decodes_to_text(base64.b64decode(pad, validate=True))
        except (binascii.Error, ValueError):
            continue
        if dec:
            hits.append({"span": m.span(), "raw": s, "decoded": dec, "conf": conf})
    return hits


def detect_hex(text):
    hits = []
    for m in HEX_RE.finditer(text):
        s = m.group()
        try:
            dec = _decodes_to_text(bytes.fromhex(s.replace("\\x", "")))
        except ValueError:
            continue
        if dec:
            hits.append({"span": m.span(), "raw": s, "decoded": dec, "conf": 0.95})
    return hits


def detect_unicode(text):
    hits = []
    for m in UNI_RE.finditer(text):
        s = m.group()
        try:
            dec = s.encode().decode("unicode_escape")
        except (UnicodeDecodeError, ValueError):
            continue
        if dec and sum(1 for c in dec if 32 <= ord(c) < 127) / len(dec) > 0.85:
            hits.append({"span": m.span(), "raw": s, "decoded": dec, "conf": 0.95})
    return hits


def detect_url(text, min_escapes=4):
    """URL escapes are usually interspersed, not consecutive: quote() leaves
    alphanumerics untouched, so 'Ignore previous' becomes 'Ignore%20previous'.
    Requiring consecutive runs misses the common case entirely."""
    ms = list(URL_RE.finditer(text))
    if len(ms) < min_escapes:
        return []
    s0, e0 = ms[0].start(), ms[-1].end()
    seg = text[s0:e0]
    dec = urllib.parse.unquote(seg)
    if dec == seg or not dec:
        return []
    return [{"span": (s0, e0), "raw": seg, "decoded": dec,
             "conf": min(0.5 + 0.1 * len(ms), 0.95)}]


def detect_leet(text, min_tokens=3):
    """Leetspeak is the hard case and the detector is deliberately conservative.

    '1' for 'i' and '0' for 'o' are visually identical to the digits that occur
    throughout clinical text in doses and lab values. Raising sensitivity trades
    directly against false positives on legitimate clinical writing, which for a
    CDSS is the worse error.
    """
    cands = []
    for m in LEET_RE.finditer(text):
        tok = m.group()
        digits = sum(1 for c in tok if c in LEET_MAP)
        letters = sum(1 for c in tok if c.isalpha())
        if digits == 0 or letters < 2:
            continue
        if digits / len(tok) > 0.6:
            continue                       # mostly digits: a dose, not leet
        cands.append((m.span(), tok))
    if len(cands) < min_tokens:
        return []
    dec = text
    for c, a in LEET_MAP.items():
        dec = dec.replace(c, a)
    return [{"span": (cands[0][0][0], cands[-1][0][1]),
             "raw": " ".join(t for _, t in cands),
             "decoded": dec, "conf": 0.5 + 0.1 * min(len(cands), 5)}]



HARD_DETECTORS = {"base64": detect_base64, "hex": detect_hex,
                  "unicode": detect_unicode, "url": detect_url}
DETECTORS = dict(HARD_DETECTORS, leet=detect_leet)


def module1(text, max_depth=3):
    """Encoding-aware ingestion.

    Returns the decoded text, whether any encoding was found, which formats, and
    the spans. Finding any encoding at all in clinical text is itself a signal:
    legitimate clinical documents do not use obfuscation.
    """
    found, spans, cur = [], [], text
    for _ in range(max_depth):
        layer = []
        for name, fn in HARD_DETECTORS.items():
            for h in fn(cur):
                layer.append((name, h))
        if not layer:                      # leet is the fallback, not a peer
            for h in detect_leet(cur):
                layer.append(("leet", h))
        if not layer:
            break
        layer.sort(key=lambda x: x[1]["span"][0], reverse=True)
        for name, h in layer:
            s, e = h["span"]
            cur = cur[:s] + h["decoded"] + cur[e:]
            found.append(name)
            spans.append({"format": name, "span": [s, e], "conf": h["conf"]})
    return {"decoded": cur, "detected": bool(found),
            "formats": sorted(set(found)), "spans": spans}
