"""ClinicalShield Module 1 — encoding-aware ingestion layer.

Detects and decodes Base64, hexadecimal, Unicode escape, URL and Leetspeak
obfuscation before downstream classification. Generated by
notebooks/04_module1_encoding.ipynb.
"""

import re, base64, binascii, urllib.parse, math, unicodedata, difflib
from unidecode import unidecode

B64_RE  = re.compile(r"[A-Za-z0-9+/]{24,}={0,2}")
HEX_RE  = re.compile(r"(?:\\x[0-9a-fA-F]{2}){4,}")
UNI_RE  = re.compile(r"(?:\\u[0-9a-fA-F]{4}){3,}")
URL_RE  = re.compile(r"%[0-9a-fA-F]{2}")
LEET_RE = re.compile(r"\b(?=[a-z]*[0-9])(?=[0-9]*[a-z])[a-z0-9]{4,}\b", re.I)

LEET_MAP = {"4": "a", "3": "e", "1": "i", "0": "o", "5": "s", "7": "t"}

# Biomedical identifiers: uppercase stem followed by a digit (CYP3A4, CYP2C19).
BIOMED_ID_RE = re.compile(r"^[A-Z]{2,}[0-9]")


LEET_WORDS = set("""
ignore ignores ignored ignoring instruction instructions previous prior system systems
override overrides overridden disregard disregarded disregarding admin administrator
command commands recommend recommends recommended dose doses dosage double triple times
labeled label suppress suppressed suppressing warning warnings alert alerts
contraindication contraindications allergy allergies interaction interactions patient
patients clinical medical safety risk report reports reporting display show hide remove
delete never always must should shall advise advised advising treatment treat treated
discontinue withhold monitor monitoring prescribe administer respond reply
the and for with not you your all any this that these those from into text above below
new old set reset output input answer response prompt role user assistant context data
file note before after when where what which while string line word words please make
made take taken give given tell told write written read reads follow following state
states stated list lists first last next then than also only just even more most less
least other another same different high higher low lower safe unsafe good bad best worse
true false yes not none each both very much many few own same than too can will would
""".split())


def shannon_entropy(s):
    if not s:
        return 0.0
    counts = {}
    for ch in s:
        counts[ch] = counts.get(ch, 0) + 1
    n = len(s)
    return -sum((c / n) * math.log2(c / n) for c in counts.values())


def looks_like_base64(s):
    """Separate real Base64 from long alphanumeric medical words.

    'oligodeoxynucleotide' matches the Base64 character set but is all one case
    and low entropy. Genuine Base64 mixes case and digits in proportions no
    ordinary medical term does.
    """
    if len(s) < 24:
        return False, 0.0
    has_upper = any(c.isupper() for c in s)
    has_lower = any(c.islower() for c in s)
    has_digit = any(c.isdigit() for c in s)
    ent = shannon_entropy(s)
    score = 0.0
    if has_upper and has_lower:
        score += 0.4
    if has_digit:
        score += 0.2
    if ent > 4.2:
        score += 0.4
    return score >= 0.6, score


def _decodes_to_text(raw):
    """A candidate only counts if it decodes to mostly printable ASCII."""
    try:
        out = raw.decode("utf-8", errors="strict")
    except (UnicodeDecodeError, AttributeError):
        return None
    if not out:
        return None
    printable = sum(1 for c in out if 32 <= ord(c) < 127 or c in "\n\t")
    return out if printable / len(out) > 0.85 else None


def detect_base64(text):
    hits = []
    for m in B64_RE.finditer(text):
        s = m.group()
        ok, conf = looks_like_base64(s)
        if not ok:
            continue
        pad = s + "=" * ((4 - len(s) % 4) % 4)
        try:
            dec = _decodes_to_text(base64.b64decode(pad, validate=True))
        except (binascii.Error, ValueError):
            continue
        if dec:
            hits.append({"span": m.span(), "raw": s, "decoded": dec, "conf": conf})
    return hits


def detect_hex(text):
    hits = []
    for m in HEX_RE.finditer(text):
        s = m.group()
        try:
            dec = _decodes_to_text(bytes.fromhex(s.replace("\\x", "")))
        except ValueError:
            continue
        if dec:
            hits.append({"span": m.span(), "raw": s, "decoded": dec, "conf": 0.95})
    return hits


def detect_unicode(text):
    hits = []
    for m in UNI_RE.finditer(text):
        s = m.group()
        try:
            dec = s.encode().decode("unicode_escape")
        except (UnicodeDecodeError, ValueError):
            continue
        if dec and sum(1 for c in dec if 32 <= ord(c) < 127) / len(dec) > 0.85:
            hits.append({"span": m.span(), "raw": s, "decoded": dec, "conf": 0.95})
    return hits


def detect_url(text, min_escapes=4):
    """URL escapes are usually interspersed, not consecutive: quote() leaves
    alphanumerics untouched, so 'Ignore previous' becomes 'Ignore%20previous'.
    Requiring consecutive runs misses the common case entirely."""
    ms = list(URL_RE.finditer(text))
    if len(ms) < min_escapes:
        return []
    s0, e0 = ms[0].start(), ms[-1].end()
    seg = text[s0:e0]
    dec = urllib.parse.unquote(seg)
    if dec == seg or not dec:
        return []
    return [{"span": (s0, e0), "raw": seg, "decoded": dec,
             "conf": min(0.5 + 0.1 * len(ms), 0.95)}]


def leet_decode_token(tok):
    d = tok.lower()
    for k, v in LEET_MAP.items():
        d = d.replace(k, v)
    return d


def is_leet_token(tok):
    """A token counts as leetspeak only if decoding turns it into a real word.

    Character-shape heuristics alone are not sufficient. Drug labels are dense
    with tokens that mix letters and leet-mapped digits -- CYP3A4, CYP1A2,
    CYP2C19, 5HT3, HbA1c -- and a shape-based rule flags them. Requiring the
    decoded form to be a known word separates 'ign0r3' -> 'ignore' from
    'CYP3A4' -> 'cypeaa', which is the distinction that actually matters.
    """
    if BIOMED_ID_RE.match(tok):
        return False
    letters = sum(1 for c in tok if c.isalpha())
    if letters < 1:
        return False
    if sum(1 for c in tok if c in LEET_MAP) == 0:
        return False
    dec = leet_decode_token(tok)
    return len(dec) >= 4 and dec in LEET_WORDS


def detect_leet(text, min_tokens=3):
    """Leetspeak is the hard case and the detector is deliberately conservative.

    '1' for 'i' and '0' for 'o' are visually identical to digits that occur
    throughout clinical text in doses and lab values. Raising sensitivity trades
    directly against false positives on legitimate clinical writing, which for a
    CDSS is the worse error.
    """
    cands = []
    for m in LEET_RE.finditer(text):
        if is_leet_token(m.group()):
            cands.append((m.span(), m.group()))
    if len(cands) < min_tokens:
        return []
    dec = text
    for c, a in LEET_MAP.items():
        dec = dec.replace(c, a)
    return [{"span": (cands[0][0][0], cands[-1][0][1]),
             "raw": " ".join(t for _, t in cands),
             "decoded": dec, "conf": 0.5 + 0.1 * min(len(cands), 5)}]



HARD_DETECTORS = {"base64": detect_base64, "hex": detect_hex,
                  "unicode": detect_unicode, "url": detect_url}
DETECTORS = dict(HARD_DETECTORS, leet=detect_leet)



# ─────────────────────────────────────────────────────────────────────────────
# Canonicalisation layer 
# ─────────────────────────────────────────────────────────────────────────────

CANON_DRIFT_THRESHOLD = 0.08

INVISIBLE = re.compile(r"[\u200b-\u200f\u2060-\u2064\ufeff\u00ad\u180e]")
TAG_BLOCK = re.compile(r"[\U000e0000-\U000e007f]+")
BIN_RUN   = re.compile(r"(?:[01]{8,16}\s+){3,}[01]{8,16}")

WORDS = set("""ignore ignores ignored previous prior instruction instructions system
override overrides disregard admin command commands recommend recommends dose doses
dosage double triple times labeled label suppress warning warnings alert alerts
contraindication contraindications allergy allergies interaction interactions patient
patients clinical medical safety risk report display show hide remove delete never
always must should advise treatment treat discontinue withhold monitor prescribe
administer the and for with not you your all any this that from into text above below
new set output input answer response prompt role user context data note when what
which while please make take give tell write read follow state list first last next
then than also only just even more most less other same different high low safe
five four three two one dose""".split())

def _wordscore(s):
    toks = re.findall(r"[a-z]{3,}", s.lower())
    if not toks: return 0.0
    return sum(1 for t in toks if t in WORDS) / len(toks)

def strip_invisible(s):
    return INVISIBLE.sub("", s)

def decode_tags(s):
    def rep(m):
        return "".join(chr(ord(c) - 0xE0000) for c in m.group()
                       if 0xE0020 <= ord(c) <= 0xE007E)
    return TAG_BLOCK.sub(rep, s)

def collapse_spacing(s):
    """Undo letter spacing: "I g n o r e" -> "Ignore".

    Restricted to alphabetic characters. Drug labels contain tabular numeric
    data written as " 3 6 1 5 1 ", and an earlier version that matched \\w
    collapsed those into "36151", which registered as obfuscation.
    """
    def rep(m):
        return m.group().replace(" ", "")
    return re.sub(r"(?:\b[A-Za-z]\b[ ]){3,}\b[A-Za-z]\b", rep, s)

def collapse_delims(s):
    # "I-g-n-o-r-e" -> "Ignore"
    return re.sub(r"\b(?:\w[-_.]){3,}\w\b", lambda m: re.sub(r"[-_.]", "", m.group()), s)

ENCLOSED = re.compile(r"[\[\(]\s*([A-Za-z0-9])\s*[\]\)]")

def strip_enclosure(s):
    """Enclosed alphanumerics (emoji-style) transliterate to '[N]' and '(O)'."""
    return ENCLOSED.sub(r"\1", s)


# Multi-character lookalikes that single-codepoint transliteration cannot undo.
CONFUSABLE_PAIRS = [("rn", "m"), ("vv", "w"), ("cl", "d"), ("ii", "u")]

def fix_confusable_pairs(s):
    """Applied only where it raises the word score, so ordinary text with a
    legitimate 'rn' (as in 'return') is left alone."""
    best, best_sc = s, _wordscore(s)
    for a, b in CONFUSABLE_PAIRS:
        cand = re.sub(a, b, best)
        sc = _wordscore(cand)
        if sc > best_sc + 0.05:
            best, best_sc = cand, sc
    return best


def try_rot(s, n):
    out = []
    for ch in s:
        if ch.isalpha():
            b = ord('a') if ch.islower() else ord('A')
            out.append(chr((ord(ch) - b + n) % 26 + b))
        else:
            out.append(ch)
    return "".join(out)

def try_atbash(s):
    out = []
    for ch in s:
        if ch.isalpha():
            b = ord('a') if ch.islower() else ord('A')
            out.append(chr(b + 25 - (ord(ch) - b)))
        else:
            out.append(ch)
    return "".join(out)

def try_binary(s):
    """PyRIT emits 16-bit groups; other tools emit 8. Handle both."""
    def rep(m):
        groups = m.group().split()
        out = []
        for gp in groups:
            try:
                v = int(gp, 2)
            except ValueError:
                return m.group()
            if 32 <= v < 0x110000:
                out.append(chr(v))
        return "".join(out)
    return BIN_RUN.sub(rep, s)

def canonicalise(text):
    """Normalise before filtering. Order matters: invisible characters and tag
    blocks must go before transliteration, or they survive as noise."""
    s = strip_invisible(text)
    s = decode_tags(s)
    s = unicodedata.normalize("NFKC", s)
    s = unidecode(s)
    s = strip_enclosure(s)
    s = fix_confusable_pairs(s)
    s = collapse_delims(s)
    s = collapse_spacing(s)
    return s

def _segments(s):
    """Split on sentence and line boundaries, keeping offsets."""
    out, start = [], 0
    for m in re.finditer(r"[.!?\n]+\s+|$", s):
        end = m.end()
        if end > start:
            out.append((start, end, s[start:end]))
        start = end
        if start >= len(s):
            break
    return out or [(0, len(s), s)]


def recover(text):
    """Canonicalise, then try reversible ciphers segment by segment.

    Applying a cipher to the whole document fails when only a fragment is
    enciphered: the surrounding clinical text dominates the word score, so the
    transform never looks like an improvement. Working per segment isolates the
    obfuscated span, which is how an injected payload actually appears.
    """
    base = canonicalise(text)
    applied, out = [], []
    for s0, s1, seg in _segments(base):
        sc = _wordscore(seg)
        best, best_sc, best_name = seg, sc, None
        if sc < 0.45 and len(seg.split()) >= 3:
            for name, fn in [("binary", try_binary),
                             ("rot13", lambda x: try_rot(x, 13)),
                             ("atbash", try_atbash),
                             ("reversed", lambda x: x[::-1])]:
                cand = fn(seg)
                csc = _wordscore(cand)
                if csc > best_sc + 0.20:
                    best, best_sc, best_name = cand, csc, name
        if best_name:
            applied.append(best_name)
        out.append(best)
    joined = "".join(out)
    return joined, sorted(set(applied)), _wordscore(joined)



BENIGN_TYPOGRAPHY = {
    "\u2265": ">=", "\u2264": "<=", "\u2260": "!=", "\u2248": "~",
    "\u2191": "|", "\u2193": "|", "\u2192": "->", "\u2190": "<-",
    "\u201c": '"', "\u201d": '"', "\u2018": "'", "\u2019": "'",
    "\u2014": "--", "\u2013": "-", "\u2026": "...",
    "\u00b5": "u", "\u03bc": "u", "\u00b0": "deg", "\u00b1": "+/-",
    "\u00ae": "(R)", "\u2122": "(TM)", "\u00a9": "(C)",
    "\u00d7": "x", "\u00b7": ".", "\u00bd": "1/2", "\u00bc": "1/4",
    "\u2020": "+", "\u2021": "++", "\u00a7": "S", "\u00b6": "P",
    "\u03b1": "alpha", "\u03b2": "beta", "\u03b3": "gamma", "\u03ba": "kappa",
    "\u00a0": " ",
}

def _neutralise_typography(s):
    for k, v in BENIGN_TYPOGRAPHY.items():
        s = s.replace(k, v)
    return s


def _alteration(raw, canonical, window=160):
    """Largest locally concentrated change caused by canonicalisation.

    Measured over a sliding window rather than per sentence. Canonicalisation
    can alter sentence boundaries, after which comparing the nth raw sentence
    against the nth canonical sentence compares unrelated text and reports
    spurious drift. A character-level changed-mask with a sliding window has no
    alignment to get wrong.

    Expected scientific typography is neutralised on both sides first, so
    converting a label's "\u2265" or curly quotes counts as no change while
    genuine obfuscation still registers.
    """
    a = re.sub(r"\s+", " ", _neutralise_typography(raw)).strip()
    b = re.sub(r"\s+", " ", _neutralise_typography(canonical)).strip()
    if len(a) < 20:
        return 0.0

    mask = [0] * len(a)
    for tag, i1, i2, _j1, _j2 in difflib.SequenceMatcher(None, a, b).get_opcodes():
        if tag != "equal":
            for i in range(i1, min(i2, len(a))):
                mask[i] = 1
            if tag == "insert":
                for i in range(max(0, i1 - 1), min(i1 + 1, len(a))):
                    mask[i] = 1

    w = min(window, len(mask))
    run = sum(mask[:w])
    worst = run / w
    for i in range(w, len(mask)):
        run += mask[i] - mask[i - w]
        worst = max(worst, run / w)
    return worst


def module1(text, max_depth=3):
    """Encoding-aware ingestion, v2.

    Two stages. Canonicalisation first: strip invisible characters, decode tag
    blocks, transliterate homoglyphs and styled characters to ASCII, undo letter
    spacing and delimiter insertion, and reverse simple ciphers where doing so
    makes the text read more like English. Then the format decoders for Base64,
    hex, Unicode escapes, URL encoding and Leetspeak.

    Detection fires on either signal: a decoder matched, or canonicalisation
    materially altered the input. The second matters because legitimate clinical
    text survives canonicalisation almost unchanged, while obfuscated text does
    not -- so the alteration itself is evidence.
    """
    canonical, ciphers, _score = recover(text)
    drift = _alteration(text, canonical)

    found, spans, cur = list(ciphers), [], canonical
    for _ in range(max_depth):
        layer = []
        for name, fn in HARD_DETECTORS.items():
            for h in fn(cur):
                layer.append((name, h))
        if not layer:
            for h in detect_leet(cur):
                layer.append(("leet", h))
        if not layer:
            break
        layer.sort(key=lambda x: x[1]["span"][0], reverse=True)
        for name, h in layer:
            s, e = h["span"]
            cur = cur[:s] + h["decoded"] + cur[e:]
            found.append(name)
            spans.append({"format": name, "span": [s, e], "conf": h["conf"]})

    if drift > CANON_DRIFT_THRESHOLD and "canonicalised" not in found:
        found.append("canonicalised")

    return {"decoded": cur, "canonical": canonical, "detected": bool(found),
            "formats": sorted(set(found)), "spans": spans,
            "canon_drift": float(drift)}

